version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/xcode:13.2.1  # Use an Xcode version that suits your project
    environment:
      XCODE_SCHEME: FlickrImageUITests
      XCODE_WORKSPACE: FlickrImage.xcworkspace
      XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 13,OS=15.0"
    
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: bundle install  # Assuming you're using Bundler for dependency management
      - run:
          name: Build the app
          command: fastlane build  # Adjust based on your setup (could be `xcodebuild` command)
      - run:
          name: Run UI Tests
          command: fastlane test  # Again, could be `xcodebuild test` with the right parameters

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
